"use client";

import { useState, useRef, DragEvent } from "react";
import JSZip from "jszip";

interface FileItem {
  name: string;
  content: string;
  type: string;
}

export default function Home() {
  const [files, setFiles] = useState<FileItem[]>([]);
  const [mainScript, setMainScript] = useState<string>("");
  const [appName, setAppName] = useState<string>("MyApp");
  const [isDragging, setIsDragging] = useState(false);
  const [isBuilding, setIsBuilding] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = async (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);

    const droppedFiles = Array.from(e.dataTransfer.files);
    await processFiles(droppedFiles);
  };

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const selectedFiles = Array.from(e.target.files);
      await processFiles(selectedFiles);
    }
  };

  const processFiles = async (fileList: File[]) => {
    const newFiles: FileItem[] = [];

    for (const file of fileList) {
      if (file.name.endsWith(".py")) {
        const content = await file.text();
        newFiles.push({
          name: file.name,
          content: content,
          type: "python",
        });

        if (!mainScript) {
          setMainScript(file.name);
        }
      }
    }

    setFiles((prev) => [...prev, ...newFiles]);
  };

  const removeFile = (index: number) => {
    setFiles((prev) => {
      const newFiles = prev.filter((_, i) => i !== index);
      if (prev[index].name === mainScript && newFiles.length > 0) {
        setMainScript(newFiles[0].name);
      } else if (newFiles.length === 0) {
        setMainScript("");
      }
      return newFiles;
    });
  };

  const generateSetupPy = () => {
    const mainFile = mainScript.replace(".py", "");

    return `from cx_Freeze import setup, Executable
import sys

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
    "packages": ["os"],
    "excludes": ["tkinter"],
    "include_files": []
}

# GUI applications require a different base on Windows
base = None
if sys.platform == "win32":
    base = "Win32GUI"  # Use "Win32GUI" for GUI apps, None for console apps

setup(
    name="${appName}",
    version="1.0",
    description="${appName} - Built with CX Freeze",
    options={"build_exe": build_exe_options},
    executables=[Executable("${mainScript}", base=base)]
)`;
  };

  const generateBuildScript = () => {
    return `@echo off
echo Building ${appName} with CX Freeze...
echo.

REM Check if Python is installed
python --version >nul 2>&1
if errorlevel 1 (
    echo Error: Python is not installed or not in PATH
    echo Please install Python from https://www.python.org/
    pause
    exit /b 1
)

REM Check if cx_Freeze is installed
python -c "import cx_Freeze" >nul 2>&1
if errorlevel 1 (
    echo Installing cx_Freeze...
    pip install cx_Freeze
    if errorlevel 1 (
        echo Error: Failed to install cx_Freeze
        pause
        exit /b 1
    )
)

REM Build the executable
echo.
echo Building executable...
python setup.py build

if errorlevel 1 (
    echo.
    echo Error: Build failed
    pause
    exit /b 1
)

echo.
echo Build completed successfully!
echo Your executable is in the 'build' folder
echo.
pause`;
  };

  const generateReadme = () => {
    return `# ${appName} - CX Freeze Build Instructions

## Prerequisites
- Python 3.6 or higher installed
- pip package manager

## Building the Executable

### Windows:
1. Double-click \`build.bat\`
2. The executable will be created in the \`build/\` directory

### Linux/Mac:
1. Open terminal in this directory
2. Run: \`chmod +x build.sh\`
3. Run: \`./build.sh\`
4. The executable will be created in the \`build/\` directory

### Manual Build:
\`\`\`bash
# Install cx_Freeze
pip install cx_Freeze

# Build the executable
python setup.py build
\`\`\`

## Files Included
${files.map((f) => `- ${f.name}`).join("\n")}

## Main Script
- ${mainScript}

## Customizing the Build
Edit \`setup.py\` to customize:
- Add packages to include
- Exclude unnecessary modules
- Include additional files
- Change executable icon (add icon_resources parameter)

## Troubleshooting
- If build fails, ensure all dependencies are installed: \`pip install -r requirements.txt\`
- For GUI applications, set base="Win32GUI" in setup.py
- For console applications, set base=None in setup.py

Generated by CX Freeze EXE Builder
`;
  };

  const generateBuildShellScript = () => {
    return `#!/bin/bash
echo "Building ${appName} with CX Freeze..."
echo

# Check if Python is installed
if ! command -v python3 &> /dev/null; then
    echo "Error: Python is not installed or not in PATH"
    echo "Please install Python from https://www.python.org/"
    exit 1
fi

# Check if cx_Freeze is installed
if ! python3 -c "import cx_Freeze" &> /dev/null; then
    echo "Installing cx_Freeze..."
    pip3 install cx_Freeze
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install cx_Freeze"
        exit 1
    fi
fi

# Build the executable
echo
echo "Building executable..."
python3 setup.py build

if [ $? -ne 0 ]; then
    echo
    echo "Error: Build failed"
    exit 1
fi

echo
echo "Build completed successfully!"
echo "Your executable is in the 'build' folder"
echo
`;
  };

  const buildProject = async () => {
    if (files.length === 0 || !mainScript) {
      alert("Please add at least one Python file and select a main script");
      return;
    }

    setIsBuilding(true);

    try {
      const zip = new JSZip();

      // Add all Python files
      files.forEach((file) => {
        zip.file(file.name, file.content);
      });

      // Add setup.py
      zip.file("setup.py", generateSetupPy());

      // Add build scripts
      zip.file("build.bat", generateBuildScript());
      zip.file("build.sh", generateBuildShellScript());

      // Add README
      zip.file("README.md", generateReadme());

      // Generate and download ZIP
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${appName}_cxfreeze_project.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setIsBuilding(false);
    } catch (error) {
      console.error("Build error:", error);
      alert("Error creating build package");
      setIsBuilding(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 p-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-800 dark:text-white mb-2">
            CX Freeze EXE Builder
          </h1>
          <p className="text-gray-600 dark:text-gray-300">
            Drag and drop your Python files to create a Windows executable
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl p-8 mb-6">
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Application Name
            </label>
            <input
              type="text"
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
              placeholder="MyApp"
            />
          </div>

          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={`border-4 border-dashed rounded-lg p-12 text-center transition-all ${
              isDragging
                ? "border-blue-500 bg-blue-50 dark:bg-blue-900/20"
                : "border-gray-300 dark:border-gray-600 hover:border-gray-400"
            }`}
          >
            <div className="mb-4">
              <svg
                className="mx-auto h-16 w-16 text-gray-400"
                stroke="currentColor"
                fill="none"
                viewBox="0 0 48 48"
              >
                <path
                  d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                  strokeWidth={2}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
            <p className="text-xl text-gray-700 dark:text-gray-300 mb-2">
              Drag and drop Python files here
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
              or
            </p>
            <button
              onClick={() => fileInputRef.current?.click()}
              className="px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
            >
              Browse Files
            </button>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept=".py"
              onChange={handleFileSelect}
              className="hidden"
            />
          </div>
        </div>

        {files.length > 0 && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl p-8 mb-6">
            <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
              Added Files ({files.length})
            </h2>

            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Main Script
              </label>
              <select
                value={mainScript}
                onChange={(e) => setMainScript(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
              >
                {files.map((file) => (
                  <option key={file.name} value={file.name}>
                    {file.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-2 mb-6">
              {files.map((file, index) => (
                <div
                  key={index}
                  className="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700 rounded-lg"
                >
                  <div className="flex items-center space-x-3">
                    <svg
                      className="h-8 w-8 text-blue-500"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4z" />
                    </svg>
                    <div>
                      <p className="font-medium text-gray-800 dark:text-white">
                        {file.name}
                        {file.name === mainScript && (
                          <span className="ml-2 px-2 py-1 text-xs bg-blue-500 text-white rounded">
                            MAIN
                          </span>
                        )}
                      </p>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        {file.content.split("\n").length} lines
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => removeFile(index)}
                    className="px-4 py-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>

            <button
              onClick={buildProject}
              disabled={isBuilding}
              className="w-full px-6 py-4 bg-green-500 text-white text-lg font-semibold rounded-lg hover:bg-green-600 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
            >
              {isBuilding ? "Generating Package..." : "Generate CX Freeze Package"}
            </button>

            <p className="text-sm text-gray-600 dark:text-gray-400 mt-4 text-center">
              This will download a ZIP file containing your Python files, setup.py, and build scripts
            </p>
          </div>
        )}

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl p-8">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
            How It Works
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300">
            <div className="flex items-start space-x-3">
              <span className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold">
                1
              </span>
              <p>Upload your Python files by dragging and dropping or browsing</p>
            </div>
            <div className="flex items-start space-x-3">
              <span className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold">
                2
              </span>
              <p>Select which Python file is your main script (entry point)</p>
            </div>
            <div className="flex items-start space-x-3">
              <span className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold">
                3
              </span>
              <p>Click "Generate CX Freeze Package" to download your build package</p>
            </div>
            <div className="flex items-start space-x-3">
              <span className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold">
                4
              </span>
              <p>Extract the ZIP file and run build.bat (Windows) or build.sh (Linux/Mac)</p>
            </div>
            <div className="flex items-start space-x-3">
              <span className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold">
                5
              </span>
              <p>Your executable will be created in the build/ directory</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
